language: csharp
solution: OpenEvent.sln
install:
  - nuget restore OpenEvent.sln
  - nuget install NUnit.Console -Version 3.12.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release OpenEvent.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./OpenEvent.Test/bin/Release/OpenEvent.Test.dll
