using System;

namespace OpenEvent.Data.Models.PaymentMethod
{
    /// <summary>
    /// Request body for adding a payment method
    /// </summary>
    public class AddPaymentMethodBody
    {
        /// <summary>
        /// User's id
        /// </summary>
        public Guid UserId { get; set; }

        /// <summary>
        /// Card token generated by Stripe.js on client
        /// </summary>
        public string CardToken { get; set; }

        /// <summary>
        /// Nickname to identify card
        /// </summary>
        public string NickName { get; set; }
    }
}